DETECTOR_RADII = [1, 2, 3, 4, 5]
NR_DETECTORS = len(DETECTOR_RADII)
DIMENSION = 2 # dimensionality of data
DATA_PATH = "output.txt"
LABEL_PATH = "parameter.txt"
BATCH_SIZE = 32
EPOCHS = 50
TRAIN = True
PADDING_LEN = 512
PAD_TOKEN = 50